---
- hosts: k8s-master
  become: true
  tasks:
    - name: Copy file with owner and permissions
      copy:
        src: cluster.yml
        dest: /tmp/cluster.yml
    - name: Copy Operator yaml 
      copy:
        src: operator.yml
        dest: /tmp/operator.yml

    - name: Disable swap
      command: kubectl create -f /tmp/operator.yaml

    - name: Disable swap
      command: kubectl create -f /tmp/cluster.yaml